spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/joboffers-web
job-offers:
  offer-fetcher:
    scheduler:
      cron: "*/10 * * * * *" #"0 */3 * * * *" # every 3 hours
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057

scheduling:
  enabled: true