spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      #when you run the app on AWS uncomment this line
      #uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}

      #when you run the app locally uncomment this line
      uri: mongodb://admin:admin@localhost:27018/joboffers-web
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
    redis:
      time-to-live: PT1H

job-offers:
  offer-fetcher:
    scheduler:
      cron: "*/30 * * * * *" #every 3 hours #"0 */3 * * * *"
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057

scheduling:
  enabled: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 30




