spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/joboffers-web
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
  cache:
    type:
    redis:
      time-to-live: PT1S

job-offers:
  offer-fetcher:
    scheduler:
      cron: "*/1 * * * * *" # every 1 seconds
    http:
      client:
        config:
          uri: http://localhost
          port: 80